services:
  s3fs:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: s3-bucket-mount:latest
    restart: unless-stopped
    env_file:
    - ./.env_aws
    volumes:
      - ${HOME}/s3:/home/s3
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    cap_drop:
      - NET_ADMIN
    